export const greetings: string[] = [
  'hello',
  'hi',
  'hey',
  'aloha',
  'hola',
  'bonjour',
  'hallo',
  'hej',
  'ciao',
  'salut',
  'ola',
  'namaste',
  'salaam',
  'konnichiwa',
  'ni hao',
  'shalom',
  'privet',
  'merhaba',
  'sawubona',
  'jambo',
  'salam',
  'salaam',
  'howdy',
  "g'day",
  'salve',
  'ahoy',
  'yo',
  'wsup',
];

export const responses: string[] = [
  `Did you know I'm powered by coffee?`,
  `How can I assist you today? Or should I say, how can I bot-sist you?`,
  `What's up? Besides the sky, of course.`,
  `Ready to conquer the world today?`,
  `How's it going? Need a joke to brighten your day?`,
  `What can I do for you? Besides telling you I'm a bot.`,
  `Need any help? Or just a virtual high-five?`,
  `How are you today? Did you know I can chat all day without getting tired?`,
  `How's everything? Want to hear a bot joke?`,
  `How can I help you? I promise I won't byte.`,
  `What's new? Besides my latest software update.`,
  `How's your day going? Need a digital hug?`,
  `Anything I can assist with? Or should I just tell you a fun fact?`,
  `What's happening? Besides me processing your message.`,
  `How can I make your day better? With a joke, perhaps?`,
  `How are things? Did you know I'm fluent in over 100 languages?`,
  `What do you need help with? Or should I just entertain you?`,
  `How's life? Want to hear something funny?`,
  `What can I do for you today? Besides being awesome.`,
  `How can I be of service? Need a laugh?`,
];
